import streamlit as st
import json
import os
import subprocess
from pathlib import Path
from whoosh.index import open_dir, exists_in
from whoosh.qparser import QueryParser
import matplotlib.pyplot as plt
import pandas as pd
from fpdf import FPDF
from collections import Counter
import datetime
from requests_tor import RequestsTor
import sys
from pathlib import Path
sys.path.append(str(Path(__file__).resolve().parents[1]))
from core.identity import rotate_identity

# --- CONFIG ---
DATA_DIR = Path("data")
ALERTS_FILE = DATA_DIR / "logs" / "alerts.json"
INDEX_DIR = DATA_DIR / "index"
LOG_DIR = DATA_DIR / "logs"
SNAPSHOT_DIR = DATA_DIR / "snapshots"
REPORT_PATH = LOG_DIR / "threat_report.md"
PDF_PATH = LOG_DIR / "threat_report.pdf"
CHART_PATH = LOG_DIR / "threat_chart.png"

# --- PAGE SETTINGS ---
st.set_page_config(page_title="DarkWeb Intel Dashboard", layout="wide")
st.title("DarkWeb Threat Intel Dashboard")
st.markdown("Stay vigilant in the neon abyss. Track your exposure on the dark web.")

# --- PDF REPORT CLASS ---
class CyberPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(0, 255, 200)
        self.cell(0, 10, "DarkWeb Threat Report", ln=1, align="C")
        self.set_draw_color(0, 255, 200)
        self.set_line_width(0.5)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(0, 255, 200)
        self.cell(0, 10, f"Generated by ghostcrawler - {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", align="C")

# --- FULL CONTROL PANEL ---
st.sidebar.title("🕹 Control Panel")
rotate_interval = st.sidebar.slider("🔄 Identity Rotate Interval", 1, 20, 5)
st.session_state["rotate_every"] = rotate_interval

if st.sidebar.button("🚀 Run Full Scan"):
    with st.spinner("Scanning the deep grid..."):
        result = subprocess.run(["python", "cli/run_scan.py"], capture_output=True, text=True)
        st.sidebar.success("Scan completed!")
        st.code(result.stdout)

if st.sidebar.button("🧼 Reset Alerts and Snapshots"):
    for folder in [LOG_DIR, SNAPSHOT_DIR, INDEX_DIR]:
        for file in folder.glob("*"):
            file.unlink()
    st.sidebar.warning("All alert logs and snapshots cleared.")

# --- PDF GENERATOR ---
def generate_threat_chart(matches):
    flat = [m.split()[0] for matchlist in matches for m in matchlist]
    counter = Counter(flat)
    labels, values = zip(*counter.items()) if counter else ([], [])
    plt.figure(figsize=(6, 3))
    plt.bar(labels, values, color="cyan")
    plt.title("Threat Type Frequency")
    plt.tight_layout()
    plt.savefig(CHART_PATH)
    plt.close()

def generate_pdf_report(alerts):
    pdf = CyberPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", size=12)
    pdf.set_text_color(255, 255, 255)
    pdf.set_fill_color(30, 30, 30)
    pdf.set_text_color(0, 255, 200)
    pdf.cell(0, 10, f"Total Alerts: {len(alerts)}", ln=True)
    pdf.ln(5)
    if CHART_PATH.exists():
        pdf.image(str(CHART_PATH), x=10, w=190)
        pdf.ln(5)
    pdf.set_text_color(255, 255, 255)
    for alert in alerts:
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(255, 100, 100)
        pdf.multi_cell(0, 10, f"[!] {alert['url']}")
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(200, 200, 200)
        for match in alert["matches"]:
            pdf.cell(0, 8, f" - {match}", ln=True)
        pdf.ln(2)
    pdf.output(str(PDF_PATH))

# --- STATS ---
st.subheader("Scan Stats")
num_alerts = 0
num_snapshots = len(list(SNAPSHOT_DIR.glob("*.html"))) if SNAPSHOT_DIR.exists() else 0
if ALERTS_FILE.exists():
    with open(ALERTS_FILE) as f:
        alerts = json.load(f)
        num_alerts = len(alerts)

st.metric("Snapshots Collected", num_snapshots)
st.metric("Alerts Detected", num_alerts)

# --- THREAT REPORT GENERATION ---
st.subheader("📄 Threat Report")
if ALERTS_FILE.exists():
    with open(ALERTS_FILE) as f:
        alerts = json.load(f)
    report_lines = ["# Threat Report\n"]
    for a in alerts:
        report_lines.append(f"## {a['url']}")
        for match in a["matches"]:
            report_lines.append(f"- {match}")
    REPORT_PATH.write_text("\n".join(report_lines))
    with open(REPORT_PATH, "r") as f:
        st.download_button("⬇️ Download Threat Report (Markdown)", f, file_name="threat_report.md")

    if st.sidebar.button("📄 Generate Cyberpunk PDF Report"):
        generate_threat_chart([a["matches"] for a in alerts])
        generate_pdf_report(alerts)
        st.sidebar.success("PDF report generated!")

    if PDF_PATH.exists():
        with open(PDF_PATH, "rb") as f:
            st.sidebar.download_button("⬇️ Download Threat Report (PDF)", f, file_name="threat_report.pdf")
else:
    st.info("No alert data to generate report.")

# --- ALERT VIEWER ---
st.subheader("Detected Threats")
if ALERTS_FILE.exists():
    with open(ALERTS_FILE) as f:
        alerts = json.load(f)
        if alerts:
            for a in alerts:
                with st.expander(f"[!] Leak on {a['url']}"):
                    for match in a["matches"]:
                        st.error(match)
        else:
            st.success("No dark web leaks detected in this scan.")
else:
    st.warning("No alerts file found. Run a scan first.")

# --- SEARCH INTERFACE ---
st.subheader("Search Dark Web Index")
query = st.text_input("Enter keyword (e.g. email, domain, term)")

if query:
    if INDEX_DIR.exists() and exists_in(INDEX_DIR):
        ix = open_dir(INDEX_DIR)
        with ix.searcher() as searcher:
            parser = QueryParser("body", ix.schema)
            parsed_query = parser.parse(query)
            results = searcher.search(parsed_query, limit=10)
            if not results:
                st.info("No results found.")
            else:
                for r in results:
                    st.write(f"**{r['title']}**")
                    st.caption(r["url"])
    else:
        st.warning("Search index not found. Run a scan first.")

# --- FOOTER ---
st.markdown("---")
st.caption("Cyberpunk-style dark web awareness dashboard. Built with love & paranoia.")